---
- name: insert variables
  shell: 
      cmd: chdir={{ ansible_env.HOME }}/massa/massa-client . <(wget -qO- https://raw.githubusercontent.com/SecorD0/Massa/main/insert_variables.sh)
  args:
      executable: /bin/bash
  register: result_wget

- name: get info insert variables
  debug: var=result_wget.stdout_lines