---
# tasks file for install_massa
- name: check for a directory massa
  stat:
      path: "{{ ansible_env.HOME }}/massa/"
  register: dir_exists

- block:
    - include_tasks: update_upgrade.yml
 
    - name: install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - jq
        - curl
        - pkg-config
        - git
        - build-essential
        - libssl-dev

    - name: get massa version
      shell:
          cmd: wget -qO- https://api.github.com/repos/massalabs/massa/releases/latest | jq -r ".tag_name"
      register: massa_version
    
    - include_tasks: working_with_archive.yml

    - name: generate service file
      template: src=massad.j2 dest=/etc/systemd/system/massad.service mode=0555
    
    - name: enable massad
      shell: 
          cmd: systemctl enable massad

    - name: daemon-reload
      ansible.builtin.systemd: 
          daemon_reload: true

    - include_tasks: open_ports.yml

    - name: check for a directory massa_backup
      stat:
          path: "{{ ansible_env.HOME }}/massa_backup"
      register: dir_exists_massa_backup
         
    - block: 
        - name: go to massa-client folder
          shell: chdir={{ ansible_env.HOME }}/massa/massa-client ./massa-client wallet_generate_private_key
          register: new_key

        - name: get new_key
          debug: var=new_key.stdout_lines
          
        - include_tasks: insert_variables.yml
        
        - name: sleep 2 second
          command: /bin/sleep 2
        
        - name: create directory massa backup
          file:
              path: "{{ ansible_env.HOME }}/massa_backup"
              state: directory

        - name: copy wallet.dat
          copy: 
              src: "{{ ansible_env.HOME }}/massa/massa-client/wallet.dat"
              dest: "{{ ansible_env.HOME }}/massa_backup/wallet.dat"
              mode: 0644
              remote_src: yes
        
        - name: copy private key 
          copy:
              src: "{{ ansible_env.HOME }}/massa/massa-node/config/node_privkey.key"
              dest: "{{ ansible_env.HOME }}/massa_backup/node_privkey.key"
              mode: 0644
              remote_src: yes
      when: not dir_exists_massa_backup.stat.exists

    - block: 
        - name: copy node_privkey.key
          copy:
              src: "{{ ansible_env.HOME }}/massa_backup/node_privkey.key"
              dest: "{{ ansible_env.HOME }}/massa/massa-node/config/node_privkey.key"
              mode: 0644
              remote_src: yes

        - name: restart massad
          ansible.builtin.systemd: 
              name: massad
              state: restarted

        - name: copy private key 
          copy:
              src: "{{ ansible_env.HOME }}/massa_backup/wallet.dat"
              dest: "{{ ansible_env.HOME }}/massa/massa-client/wallet.dat"
              mode: 0644
              remote_src: yes
        - include_tasks: insert_variables.yml

      when: dir_exists_massa_backup.stat.exists
      
    - name: go to root folder
      shell: chdir=/ ls
  when: not dir_exists.stat.exists