---
 - name: Installing coin massa
   hosts: "{{ list_hosts }}"
   become: true

   vars:
       temp: 
   
   tasks:

     - name: check for a directory
       stat:
           path: $HOME/massa/
           register: dir_exists
     - block:
         - name: update and upgrade apt packages
           apt:
               upgrade: true
               update_cache: true
               cache_valid_time: 86400

         - name: installing application
           shell: "apt install jq curl pkg-config git build-essential libssl-dev -y"
           register: result_installing

         - name: get results installing
           debug: var=result_installing.stdout_lines

         - name: shell --version
           shell:
               cmd: wget -qO- https://api.github.com/repos/massalabs/massa/releases/latest | jq -r ".tag_name"
           register: massa_version
          
         - name: load archive
           shell:
               cmd: wget -qO $HOME/massa.tar.gz "https://github.com/massalabs/massa/releases/download/{{ massa_version.stdout }}/massa_{{ massa_version.stdout }}_release_linux.tar.gz"

         - name: unpack archive
           shell:
               cmd: tar -xvf $HOME/massa.tar.gz

         - name: delete archive
           shell:
               cmd: rm -rf $HOME/massa.tar.gz

         - name: chmod files
           shell:
               cmd: chmod +x $HOME/massa/massa-node/massa-node $HOME/massa/massa-client/massa-client

         - name: create file service
           copy:
               dest: "/etc/systemd/system/massad.service"
               content: |
                   [Unit]
                   Description=Massa Node
                   After=network-online.target

                   [Service]
                   User=$USER
                   WorkingDirectory=$HOME/massa/massa-node
                   ExecStart=$HOME/massa/massa-node/massa-node
                   Restart=on-failure
                   RestartSec=3
                   LimitNOFILE=65535

                   [Install]
                   WantedBy=multi-user.target

         - name: enable massad
           shell: "systemctl enable massad"

         - name: daemon-reload
           shell: "systemctl daemon-reload"

         # open_ports
         - name: open_ports stop massad
           shell: "systemctl stop massad"

         - name: open_ports open ports
           shell: 
               cmd: . <(wget -qO- https://raw.githubusercontent.com/SecorD0/utils/main/miscellaneous/ports_opening.sh) 31244 31245
           args:
               executable: /bin/bash

         - name: open_ports tee
           shell: |
               tee <<EOF >/dev/null $HOME/massa/massa-node/config/config.toml
               [network]
               routable_ip = "`wget -qO- eth0.me`"
               EOF
           args:
               executable: /bin/bash

         - name: open_ports install net-tools
           apt: 
               name: net-tools
               state: latest

         - name: open_ports netstat
           shell: 
               cmd: netstat -ntlp | grep "massa-node"

         - name: open_ports restart massad
           shell: 
               cmd: systemctl restart massad
         # end open_ports

         - name: go to massa-client folder
           shell: chdir=$HOME/massa/massa-client/

         - name: check for a directory massa_backup
           stat:
               path: $HOME/massa_backup
           register: dir_exists_massa_backup

         # if not exist massa_backup
         - name: generate private key 
           shell: "./massa-client wallet_generate_private_key"
           when: not dir_exists_massa_backup.stat.exists
         # else
         - name: copy node_privkey.key
           ansible.builtin.copy:
               src: $HOME/massa_backup/node_privkey.key
               dest: $HOME/massa/massa-node/config/node_privkey.key
               mode: '0555'
           when: dir_exists_massa_backup.stat.exists

         - name: restart massad
           shell: 
               cmd: systemctl restart massad
           when: dir_exists_massa_backup.stat.exists

         - name: copy private key 
           ansible.builtin.copy:
               src: $HOME/massa_backup/wallet.dat
               dest: $HOME/massa/massa-client/wallet.dat
               mode: '0555'
           when: dir_exists_massa_backup.stat.exists
         # end if

         - name: wget insert variables
           shell: ". <(wget -qO- https://raw.githubusercontent.com/SecorD0/Massa/main/insert_variables.sh)"
           args:
               executable: /bin/bash
           register: result_wget

         - name: get wget
           debug: var=result_wget.stdout_lines

         # if not exist massa_backup
         - name: create directory massa backup
           file:
               path: $HOME/massa_backup
               state: directory
           when: not dir_exists_massa_backup.stat.exists

         - name: copy wallet.dat
           ansible.builtin.copy:
               src: $HOME/massa/massa-client/wallet.dat
               dest: $HOME/massa_backup/wallet.dat
               mode: '0555'
           when: not dir_exists_massa_backup.stat.exists

         - name: copy private key 
           ansible.builtin.copy:
               src: $HOME/massa/massa-node/config/node_privkey.key
               dest: $HOME/massa_backup/node_privkey.key
               mode: '0555'
           when: not dir_exists_massa_backup.stat.exists
         # end if
         
         - name: go to root folder
           shell: chdir=/
       when: not dir_exists.stat.exists