---
 - name: restarting the solana service (test net)
   hosts: "{{ list_hosts }}"
   become: true

   vars:
     solana: /root/.local/share/solana/install/active_release/bin

   tasks:

   - name: stop solana service
     shell: "systemctl stop solana.service && cd /root/solana/solana-snapshot-finder"

   - name: delete ledger
     file:
         state: absent
         path: /root/solana/ledger/

   - name: load ledger
     shell: source ./venv/bin/activate && python3 snapshot-finder.py --snapshot_path $HOME/solana/ledger -r http://api.testnet.solana.com
     args:
         executable: /bin/bash
     register: result_load_ledger

   - name: get results load ledger
     debug: var=result_load_ledger.stdout_lines

   - name: start solana service
     shell: "systemctl start solana.service"