---
 - name: replace text in file
   hosts: "{{ list_hosts }}"
   become: true

   tasks:
   
   - name: delete file
     file: 
        path: /root/tmp.info
        state: absent

   - name: create file
     command: /usr/bin/touch /root/tmp.info

  # - name: create a new file and add empty line
  #   lineinfile:
  #      dest: /root/tmp.info
  #      regexp: '^'
  #      line: ''
  #      state: present
  #      create: True

  # - name: replace empty line in file
  #   lineinfile: 
  #      dest: /root/tmp.info
  #      regexp: '^'
  #      line: 'this is a new line'
  #      state: present

   - name: add new lines in file
     lineinfile:
        dest: /root/tmp.info
        line: "{{ item }}"
        state: present
     with_items:
         - 'Environment="SOLANA_METRICS_CONFIG=host=https://metrics.solana.com:8086,db=tds,u=testnet_write,p=c4fa841aa918bf8274e3e2a44d77568d9861b3ea"'
         - 'ExecStart=/root/.local/share/solana/install/active_release/bin/solana-validator \'
         - '--entrypoint entrypoint.testnet.solana.com:8001 \'
         - '--entrypoint entrypoint2.testnet.solana.com:8001 \'