---
 - name: test play book
   hosts: not_ek_srv
   become: true

   vars:
     solana: /root/.local/share/solana/install/active_release/bin

   tasks:

  # - name: copy solana.service
  #   copy: 
  #      src: /home/user/work/test.txt
  #      dest: /root/test.txt
  #      mode: 0644
  #      backup: yes

   - name: c
     shell: "tail -n 5000 /root/solana/solana.log | grep visible"
     register: result_stop

   - name: get results stop
     debug: var=result_stop.stdout

    #- name: get massa version
    #  shell:
    #      cmd: wget -qO- https://api.github.com/repos/massalabs/massa/releases/latest | jq -r ".tag_name"
    #  register: massa_version
   
    #- name: load archive
    #  shell:
    #      cmd: wget -qO {{ ansible_env.HOME }}/massa.tar.gz "https://github.com/massalabs/massa/releases/download/{{ massa_version.stdout }}/massa_{{ massa_version.stdout }}_release_linux.tar.gz"

    #- name: unpack archive
    #  shell:
    #      cmd: tar -xvf {{ ansible_env.HOME }}/massa.tar.gz

    #- name: delete archive
    #  shell:
    #      cmd: rm -rf {{ ansible_env.HOME }}/massa.tar.gz
    #- name: shell --version
    #  shell:
    #      cmd: wget -qO- https://api.github.com/repos/massalabs/massa/releases/latest | jq -r ".tag_name"
    #  register: massa_version
    #      
    #- name: load archive
    #  shell:
    #      cmd: wget -qO $HOME/massa.tar.gz "https://github.com/massalabs/massa/releases/download/{{ massa_version.stdout }}/massa_{{ massa_version.stdout }}_release_linux.tar.gz"

    #- name: view
    #  debug: var=massa_version.stdout_lines
    #- name: create file service
    #  copy:
    #   dest: "/root/test.service"
    #    content: |
    #        [Unit]
    #        Description=Massa Node
    #        After=network-online.target

    #        [Service]
    #        User=$USER
    #        WorkingDirectory=$HOME/massa/massa-node
    #        ExecStart=$HOME/massa/target/release/massa-node
    #        Restart=on-failure
    #        RestartSec=3
    #        LimitNOFILE=65535

    #        [Install]
    #        WantedBy=multi-user.target