---
 - name: test play book
   hosts: "{{ list_hosts }}"
   become: true

   tasks:
   - name: update and upgrade apt packages
     apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400
     register: result

   - name: get results stop
     debug: var=result.stdout_lines
