---
- name: update sui db
  hosts: sui
  become: true

  tasks:

  - name: Download sh
    get_url: 
      url: https://raw.githubusercontent.com/EvgeniiPerkin/scripts/main/update_db_sui.sh
      dest: /root/
      mode: 0777
    
  - name: Execute the update_db_sui.sh
    shell: /bin/bash /root/update_db_sui.sh
    register: output_sh

  - name: Print result
    debug: var=output_sh.stdout

  - name: Remove the update_db_sui.sh
    file: 
      path: /root/update_db_sui.sh 
      state: absent